### PR TITLE
Comprehension 1: Basic Methods

### PR DESCRIPTION
**Pull request by Hamled**
This PR adds a single, short worksheet with problems covering basic methods (single, scalar parameter and no loop constructs inside of the body).

I plan to add another two worksheets for comprehension practice on methods:
- [ ] Advanced Methods - this would cover array/hash/more complex parameters and loops / enumerable methods in the body
- [ ] Method composition - this would cover examples that involve multiple methods

NOTE: I've put this in its own repo for now just so I can have a place for y'all to review it. I expect that we'll want to move this into a different repo at some point, I'm open to suggestions. Probably in the exercises folder for textbook-curriculum?

### CODE REVIEW

**Comment by Hamled** [comment]
[Early Ruby practice worksheets](https://trello.com/c/dRbunb3C/910-early-ruby-practice-worksheets)

**Review by tildeee — APPROVED** [review]
I really like this!

The intro is great!

A lot of these _are_ nuanced understandings of Ruby, which I **really** like. I'd be totally comfortable asking each student to go through it. I wish I could get every student to look through it if we made it optional... I'm torn about making it required, because then I feel like reviewing it in class would be a huge pain, where the answer would mostly be, "That's how Ruby works!!" which is not my favorite response.

Anyway, I'm rambling, I like it a lot!

**Review by shrutivanw — APPROVED** [review]
:+1: This is great! 
Aside: since you're thinking of further exercises, I'd like to share the slide deck from Day 2 of JSL. These classroom exercises include common errors I've seen while reviewing code during JSL. Check if it makes sense to include any of these for the complete cohort (instead of just JSL students). https://drive.google.com/open?id=139tDd7Ft6Vy0-7mlVxkA-uOnHq6Q3UTgInv-iVIgX0g

**Comment by Hamled** [comment]
Thanks for the link @shrutivanw! I will check out those slides and see if there are any additions to this worksheet or future ones which I can incorporate!

Merging this in for now, though.

**Pull request merged**
